DROP SCHEMA IF EXISTS POTENCIAR_SOLIDARIO;
CREATE SCHEMA IF NOT EXISTS POTENCIAR_SOLIDARIO;
USE POTENCIAR_SOLIDARIO;

DROP TABLE IF EXISTS PROVEEDORES;
CREATE TABLE IF NOT EXISTS PROVEEDORES(
NUMERO_PROVEEDOR VARCHAR(10) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
CUIT_PROVEEDOR VARCHAR(50) NOT NULL,
CATEGORIA_PROVEEDOR ENUM('Materiales', 'Servicios', 'Agente Impositivo', 'Agroindustria', 'Construccion','Consultoria', 'Consultoria IT', 'Energia Eolica', 'Energia Renovable', 'Energia Solar', 'Software','Tecnologia','Transporte') NOT NULL,
MAIL VARCHAR(60) NOT NULL,
TELEFONO VARCHAR(20) NOT NULL,
RAZON_SOCIAL ENUM('S.R.L.', 'S.A.', 'Cooperativa'),
PAIS_PROVEEDOR VARCHAR(30) NOT NULL,
CIUDAD_PROVEEDOR VARCHAR(40) NOT NULL,
CONSTRAINT PK_PROVEEDORES PRIMARY KEY(NUMERO_PROVEEDOR)
);

DROP TABLE IF EXISTS EGRESOS;
CREATE TABLE IF NOT EXISTS EGRESOS(
ID_EGRESO INT AUTO_INCREMENT,
NUMERO_CUENTA INT NOT NULL,
NUMERO_PROVEEDOR VARCHAR(10) NOT NULL,
IMPORTE DECIMAL(8,2) NOT NULL,
FECHA TIMESTAMP NOT NULL,
CONSTRAINT PK_PROVEEDORES PRIMARY KEY(ID_EGRESO),
CONSTRAINT FK_EGRESOS_PROVEEDORES FOREIGN KEY (NUMERO_PROVEEDOR)
REFERENCES PROVEEDORES(NUMERO_PROVEEDOR)
);

DROP TABLE IF EXISTS EMPLEADOS;
CREATE TABLE IF NOT EXISTS EMPLEADOS(
ID_EMPLEADO INT AUTO_INCREMENT,
NOMBRE_EMPLEADO VARCHAR(50) NOT NULL,
DNI INT NOT NULL,
MAIL VARCHAR(50) NOT NULL,
TELEFONO INT NOT NULL,
CONSTRAINT PK_EMPLEADOS PRIMARY KEY(ID_EMPLEADO) 
);

DROP TABLE IF EXISTS DONANTES;
CREATE TABLE IF NOT EXISTS DONANTES(
ID_DONANTE VARCHAR(15) NOT NULL,
NOMBRE_DONANTE VARCHAR(50) NOT NULL,
RAZON_SOCIAL ENUM('GOB', 'ONG',  'S.R.L.', 'S.A.', 'S.A.S.') NOT NULL,
CUIT_DONANTE VARCHAR(50) NOT NULL,
ALTA DATE NOT NULL,
TIPO_CONTRIBUYENTE ENUM('Responsable Inscripto', 'Exento', 'Monotributista', '-') NOT NULL,
ACTIVO ENUM('SI', 'NO') NOT NULL,
FRECUENCIA_DONACION ENUM('Anual', 'Mensual', 'Bimestral',  'Trimestral', 'Semestral') NOT NULL,
PAIS_DONANTE VARCHAR(30) NOT NULL,
CONSTRAINT PK_DONANTES PRIMARY KEY(ID_DONANTE) 
);

DROP TABLE IF EXISTS DONACIONES;
CREATE TABLE IF NOT EXISTS DONACIONES(
ID_DONACION INT AUTO_INCREMENT,
ID_DONANTE VARCHAR(15) NOT NULL,
IMPORTE DECIMAL(8,2) NOT NULL,
NUMERO_CUENTA INT NOT NULL,
FECHA_DONACION DATE NOT NULL,
CONSTRAINT PK_DONACIONES PRIMARY KEY(ID_DONACION),
CONSTRAINT FK_DONACIONES_DONANTES FOREIGN KEY(ID_DONANTE)
REFERENCES DONANTES(ID_DONANTE)
);
